import { mockSession } from './auth.js';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const fmt=n=>'US$ '+Number(n).toLocaleString('en-US',{maximumFractionDigits:0});
const icon=p=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">${p}</svg>`;
const icons={dash:icon('<path d="M3 13h8V3H3zM13 21h8V11h-8zM13 3h8v6h-8zM3 21h8v-6H3z"/>'),ops:icon('<path d="M3 17l6-6 4 4 8-8"/><path d="M14 7h7v7"/>'),soc:icon('<path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M23 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/>'),port:icon('<path d="M3 7h18M5 7v14h14V7M8 7V5a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/>'),ret:icon('<path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><path d="M7 10l5 5 5-5"/><path d="M12 15V3"/>'),roles:icon('<path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10"/><path d="M9 12l2 2 4-4"/>'),cont:icon('<path d="M4 4h16v16H4z"/><path d="M8 8h8M8 12h8M8 16h4"/>'),audit:icon('<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><path d="M14 2v6h6"/><path d="M9 15l2 2 4-4"/>')};
const menu=[['dashboard','Resumen',icons.dash],['operaciones','Operaciones',icons.ops],['socios','Socios',icons.soc],['portafolios','Portafolios',icons.port],['retiros','Retiros',icons.ret],['permisos','Perfiles y permisos',icons.roles],['contenido','Contenido',icons.cont],['auditoria','Auditoría',icons.audit]];
const names=['Juan Pérez','Pedro Gómez','Luis Álvarez','Toto Rojas','Pepe Iglesias','Marina Soto','Diego Vega','Ana Ruiz','Sofía Bruno','Martín Díaz','Camila Rivas','Nicolás Arias','Lucía Campos','Mateo Silva','Paula León','Iván Núñez','Valeria Torres','Bruno Costa','Agustina Molina','Julián Vega'];
const socios=Array.from({length:60},(_,i)=>({id:`MSTR-${rand(4)}-${rand(4)}`,nombre:names[i%names.length],email:`socio${i+1}@elmaster.vip`,kyc:i%9?'Aprobado':'Pendiente',capital:[8000,10000,15000,25000,50000][i%5],ganancia:Math.round(520+i*137+(i%7)*280),perfil:i%11?'Socio':'Empleado',desde:`${String((i%28)+1).padStart(2,'0')}/0${(i%8)+1}/2026`}));
const ops=Array.from({length:65},(_,i)=>({id:`OP-${4280+i}`,activo:['NASDAQ','BTC/USD','SP500','EUR/USD','USD/JPY','ETH/USD','GOLD','TSLA'][i%8],tipo:i%3?'LONG':'SHORT',monto:1000+(i%12)*750,res:i%5===0?-(80+i*3):(120+i*18),estado:['abierta','cerrada','pendiente'][i%3],comision:Math.abs(18+i*1.8)}));
const retiros=Array.from({length:24},(_,i)=>({id:`RT-${1050+i}`,fecha:`${String((i%28)+1).padStart(2,'0')}/05/2026`,monto:300+(i%8)*250,cuenta:i%2?'USDT TRC20 · Tw...9aFt':'Banco Galicia · ****4421',estado:['Solicitado','En revisión','Transferido','Cerrado'][i%4]}));
const notes=['Aprobó retiro RT-1051','Cierre automático de operación OP-4271 (+US$ 412)','Cargó análisis “Fed mantiene tasas”','KYC aprobado para MSTR-7KLD-A29P','Nuevo socio inversor pendiente'];
function rand(n){return Array.from({length:n},()=> 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'[Math.floor(Math.random()*32)]).join('')}
let state={page:'dashboard',theme:localStorage.theme||'dark'};
function init(){document.documentElement.classList.toggle('light',state.theme==='light'); $('#themeIcon').textContent=state.theme==='light'?'☀️':'🌙'; $('#menu').innerHTML=menu.map(m=>`<button class="nav-item" data-page="${m[0]}">${m[2]}<span class="nav-label">${m[1]}</span></button>`).join(''); $$('#menu .nav-item').forEach(b=>b.onclick=()=>render(b.dataset.page)); $('#toggleSidebar').onclick=()=>{ if(innerWidth<980) $('#sidebar').classList.toggle('open'); else $('#sidebar').classList.toggle('collapsed')}; $('#themeBtn').onclick=()=>{state.theme=state.theme==='light'?'dark':'light';localStorage.theme=state.theme;init()}; $('#fullBtn').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen(); $('#logoutBtn').onclick=()=>Swal.fire('Sesión cerrada','Demo local lista para conectar a Supabase.','success'); $('#avatarInput').onchange=e=>{const f=e.target.files[0]; if(f) $('#avatarImg').src=URL.createObjectURL(f)}; $('#notifyPop').innerHTML=notes.map(n=>`<div class="note">${n}<br><small>hace ${Math.ceil(Math.random()*50)} min</small></div>`).join(''); pwa(); render(state.page)}
function pwa(){ if('serviceWorker'in navigator) navigator.serviceWorker.register('./sw.js'); let deferred; window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;$('#installBanner').classList.add('show')}); $('#btnInstall').onclick=async()=>{ if(deferred){deferred.prompt();deferred=null}else Swal.fire('Instalación','En Chrome/Edge usá “Instalar aplicación” desde el menú del navegador.','info')}; $('#btnCloseInstall').onclick=()=>$('#installBanner').classList.remove('show'); setTimeout(()=>$('#installBanner').classList.add('show'),700)}
function render(page){state.page=page; $$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.page===page)); $('#pageTitle').textContent=menu.find(m=>m[0]===page)?.[1]||'Backoffice'; const views={dashboard,operaciones,socios,portafolios,retiros,permisos,contenido,auditoria}; $('#content').innerHTML=views[page](); setTimeout(charts,50); if(innerWidth<980) $('#sidebar').classList.remove('open')}
function metrics(){return `<div class="grid cards"><div class="card metric"><span>Capital total del fondo</span><strong>${fmt(socios.reduce((a,s)=>a+s.capital,0))}</strong></div><div class="card metric"><span>Ganancia acumulada</span><strong class="gain">${fmt(socios.reduce((a,s)=>a+s.ganancia,0))}</strong></div><div class="card metric"><span>Comisiones generadas</span><strong class="gold">${fmt(ops.reduce((a,o)=>a+o.comision,0))}</strong></div><div class="card metric"><span>Socios activos</span><strong>${socios.length}</strong></div></div>`}
function dashboard(){return `${metrics()}<div class="grid two"><div class="card"><h2>Capital operativo</h2><p>Evolución diaria del fondo</p><canvas id="areaChart" height="120"></canvas></div><div class="card"><h2>Pendientes</h2>${['KYC pendiente · 7 socios','Retiro RT-1054 solicitado','Operación OP-4280 abierta','Permiso nuevo a revisar'].map(x=>`<div class="task">${x}<span class="badge warn" style="float:right">Revisar</span></div>`).join('')}</div></div><div class="grid three"><div class="card"><h2>Exposición</h2><canvas id="donutChart"></canvas></div><div class="card"><h2>Rendimiento por día</h2><canvas id="barChart"></canvas></div><div class="card"><h2>Bitácora rápida</h2>${notes.map(n=>`<div class="task"><b>${n}</b><div class="mini">Sistema · hash simulado</div></div>`).join('')}</div></div>`}
function operaciones(){return `<div class="grid two"><div class="card"><h2>Cargar nueva operación</h2><div class="form"><select><option>NASDAQ</option><option>BTC/USD</option><option>SP500</option></select><select><option>LONG</option><option>SHORT</option></select><input value="5000"><button onclick="Swal.fire('Operación creada','Registro simulado agregado a la cola.','success')" class="btn primary">+ Abrir operación</button></div></div><div class="card"><h2>Operaciones del Master</h2><canvas id="areaChart" height="110"></canvas></div></div>${table(ops,'ops')}`}
function socios(){return `<div class="card"><h2>Socios del Club</h2><p>Solo SuperAdmin/Empleados autorizados ven nombres reales. IDs públicos encriptados.</p><button class="btn primary" onclick="Swal.fire('Invitación enviada','Nuevo enlace seguro generado.','success')">+ Invitar socio</button></div>${table(socios,'socios')}`}
function portafolios(){return `${metrics()}<div class="grid two"><div class="card"><h2>Distribución de portafolio</h2><canvas id="donutChart"></canvas></div><div class="card"><h2>Performance mensual</h2><canvas id="barChart"></canvas></div></div>${table(socios.slice(0,40).map((s,i)=>({...s,risk:['Bajo','Medio','Alto'][i%3],alloc:['Índices 45% · Cripto 20% · Cash 35%','FX 35% · Acciones 40% · Cash 25%','Índices 60% · Bonos 20% · Cash 20%'][i%3]})),'portfolio')}`}
function retiros(){return `<div class="card"><h2>Cola de retiros</h2><p>Validación KYC, cuenta destino y auditoría antes de aprobar.</p></div>${table(retiros,'retiros')}`}
function permisos(){return `<div class="grid three">${['SuperAdmin','Empleados','Socios'].map((r,i)=>`<div class="card"><h2>${r}</h2><p>${['Control total, usuarios, permisos, auditoría y finanzas.','Operaciones, contenidos, KYC y soporte según permisos.','Visualiza su portafolio, rentabilidad, reportes y retiros.'][i]}</p><button class="btn aqua" onclick="Swal.fire('Permisos','Matriz de permisos actualizada.','success')">Gestionar permisos</button></div>`).join('')}</div><div class="card"><h2>Matriz de permisos</h2><div class="table-wrap"><table><tr><th>Módulo</th><th>SuperAdmin</th><th>Empleados</th><th>Socios</th></tr>${['Dashboard','Operaciones','Socios','Portafolios','Retiros','Contenido','Auditoría'].map((m,i)=>`<tr><td>${m}</td><td><span class="badge ok">Total</span></td><td><span class="badge ${i>4?'warn':'ok'}">${i>4?'Limitado':'Editar'}</span></td><td><span class="badge ${i===0||i===3?'ok':'bad'}">${i===0||i===3?'Ver':'Sin acceso'}</span></td></tr>`).join('')}</table></div></div>`}
function contenido(){return `<div class="grid two"><div class="card"><h2>Publicar análisis</h2><div class="form"><input placeholder="Título del análisis"><select><option>Macro</option><option>Mercado</option><option>Riesgo</option></select><textarea rows="6" placeholder="Resumen del análisis..."></textarea><button class="btn primary" onclick="Swal.fire('Publicado','El análisis quedó disponible para socios.','success')">Publicar</button></div></div><div class="card"><h2>Cargar video</h2><div class="form"><input placeholder="URL del video"><input placeholder="Título"><input placeholder="Operación vinculada opcional"><button class="btn primary" onclick="Swal.fire('Video cargado','Contenido vinculado al backoffice.','success')">Cargar video</button></div></div></div>`}
function auditoria(){return `<div class="card"><h2>Bitácora de eventos</h2><p>Registro inmutable preparado para firma hash en producción.</p>${Array.from({length:32},(_,i)=>`<div class="task"><b>${notes[i%notes.length]}</b><span class="badge ${i%3?'ok':'warn'}" style="float:right">${['kyc','op','retiro'][i%3]}</span><div class="mini">${i%2?'Admin':'Sistema'} · hash SHA-256 simulado · hace ${i+1}h</div></div>`).join('')}</div>`}
function table(data,type){let rows=data.map((x,i)=>{ if(type==='socios')return `<tr><td class="gold"><b>${x.id}</b></td><td>${x.nombre}</td><td>${x.email}</td><td><span class="badge ${x.kyc==='Aprobado'?'ok':'warn'}">${x.kyc}</span></td><td>${fmt(x.capital)}</td><td class="gain">+${fmt(x.ganancia)}</td><td>${x.desde}</td></tr>`; if(type==='ops')return `<tr><td>${x.id}</td><td><b>${x.activo}</b></td><td>${x.tipo}</td><td>${fmt(x.monto)}</td><td class="${x.res>0?'gain':'loss'}">${x.res>0?'+':''}${fmt(x.res)}</td><td class="gold">${fmt(x.comision)}</td><td><span class="badge ${x.estado==='abierta'?'ok':x.estado==='pendiente'?'warn':'bad'}">${x.estado}</span></td></tr>`; if(type==='retiros')return `<tr><td>${x.id}</td><td>${x.fecha}</td><td><b>${fmt(x.monto)}</b></td><td>${x.cuenta}</td><td><span class="badge ${x.estado==='Transferido'?'ok':x.estado==='Cerrado'?'bad':'warn'}">${x.estado}</span></td><td><button class="btn" onclick="Swal.fire('Revisión','Acción simulada para ${x.id}.','info')">Revisar</button></td></tr>`; return `<tr><td>${x.id}</td><td>${x.nombre}</td><td>${fmt(x.capital)}</td><td class="gain">+${fmt(x.ganancia)}</td><td>${x.risk}</td><td>${x.alloc}</td></tr>`}).join(''); let head={socios:'<th>ID anónimo</th><th>Nombre real</th><th>Email</th><th>KYC</th><th>Capital</th><th>Ganancia</th><th>Activo desde</th>',ops:'<th>ID</th><th>Activo</th><th>Tipo</th><th>Monto</th><th>Resultado</th><th>Comisión</th><th>Estado</th>',retiros:'<th>Ticket</th><th>Solicitud</th><th>Monto</th><th>Cuenta</th><th>Estado</th><th>Acciones</th>',portfolio:'<th>ID</th><th>Socio</th><th>Capital</th><th>Ganancia</th><th>Riesgo</th><th>Asignación</th>'}[type]; return `<div class="card"><div class="table-wrap"><table><thead><tr>${head}</tr></thead><tbody>${rows}</tbody></table></div></div>`}
function charts(){Chart.defaults.color=getComputedStyle(document.documentElement).getPropertyValue('--muted'); Chart.defaults.borderColor='rgba(128,128,128,.15)'; const line=$('#areaChart'); if(line)new Chart(line,{type:'line',data:{labels:['Ene','Feb','Mar','Abr','May','Jun','Jul','Ago','Sep','Oct','Nov','Dic'],datasets:[{label:'Capital',data:[82,86,90,94,102,110,117,126,131,139,151,169],fill:true,tension:.42,borderColor:'#45b9ad',backgroundColor:'rgba(69,185,173,.18)'}]},options:{plugins:{legend:{display:false}},responsive:true}}); const d=$('#donutChart'); if(d)new Chart(d,{type:'doughnut',data:{labels:['Índices','FX','Cripto','Cash'],datasets:[{data:[42,24,18,16],backgroundColor:['#45b9ad','#ffde59','#6aa6ff','#f2f2f2']}]} ,options:{plugins:{legend:{position:'bottom'}}}}); const b=$('#barChart'); if(b)new Chart(b,{type:'bar',data:{labels:['Lun','Mar','Mié','Jue','Vie'],datasets:[{data:[2.1,3.4,4.8,5.2,3.9],backgroundColor:'#45b9ad',borderRadius:8}]},options:{plugins:{legend:{display:false}}}})}
init();
